# This file is the manifest for the LoggingDummy consumer plugin.
# It defines the configuration and metadata required for the plugin to function within the batcontrol system.
implementation_class: logging_dummy.LoggingDummy
required_config:
  - prefix

required_alpine_packages:
  - python3
  - py3-numpy
  - py3-requests

## currently unused
required_python_modules:
  - pyyaml
  - logging
  - os
  - sys
  - time
  - random
  - string
  - json
  - datetime
  - socket
  - requests
  - urllib3
  - logging
