timezone: Europe/Berlin #your time zone. not optional.
loglevel: debug
max_logfile_size: 100 #kB
battery_control:
  min_price_difference: 0.05 # minimum price difference in Euro to justify charging your battery
  always_allow_discharge_limit: 0.90 # 0.00 to 1.00 above this SOC limit using energy from the battery is always allowed
  max_charging_from_grid_limit: 0.90 # 0.00 to 1.00 charging from the grid is only allowed until this SOC limit
inverter:
  type: fronius_gen24 #currently only fronius_gen24 supported
  address: 192.168.0.XX # the local IP of your inverter. needs to be reachable from the machine that runs batcontrol
  user: customer #customer or technician lowercase only!!
  password: YOUR-PASSWORD #
  max_grid_charge_rate: 5000 # Watt
  max_pv_charge_rate : 3000 # Watt
utility:
  type: tibber # [tibber, awattar_at, awattar_de, evcc]
  apikey: YOUR-PASSWORD # only required for tibber get one from https://developer.tibber.com/ Zz-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
  vat: 0.20 # only required for awattar
  fees: 0.015 # only required for awattar
  markup: 0.03 # only required for awattar
  url: http://evcc.local/api/tariff/grid # only required for evcc
mqtt:
  enabled: false
  logger: false
  broker: localhost
  port: 1883
  topic: batcontrol
  username: user
  password: password
  tls: false
  cafile: /etc/ssl/certs/ca-certificates.crt
  certfile: /etc/ssl/certs/client.crt
  keyfile: /etc/ssl/certs/client.key
  tls_version: tlsv1.2

heatpump:
  type: Thermia # [Thermia, none]
  user: "your_username"  # Username for accessing the heat pump system
  password: "your_password"  # Password for accessing the heat pump system
  # EVU block settings
  min_price_for_evu_block: 0.6  # Minimum price threshold to block EVU (Energy Supply Company) usage
  max_evu_block_hours: 14  # Maximum number of hours to block EVU usage per day
  max_evu_block_duration: 6  # Maximum duration for a single EVU block event in hours
  # Hot water block settings
  min_price_for_hot_water_block: 0.4  # Minimum price threshold to block hot water usage
  max_hot_water_block_hours: 10  # Maximum number of hours to block hot water usage per day
  max_hot_water_block_duration: 4  # Maximum duration for a single hot water block event in hours
  #reduced heat settings
  min_price_for_reduced_heat: 0.3  # Minimum price threshold to reduce heating
  max_reduced_heat_hours: 14  # Maximum number of hours to reduce heating per day
  max_reduced_heat_duration: 6  # Maximum duration for a single reduced heating event in hours
  reduced_heat_temperature: 20  # Target temperature when heating is reduced
  #increased heat settings
  max_price_for_increased_heat: 0.2  # Maximum price threshold to increase heating
  min_energy_surplus_for_increased_heat: 1000  # Minimum energy surplus required to increase heating
  max_increased_heat_hours: 14  # Maximum number of hours to increase heating per day
  max_increased_heat_duration: 6  # Maximum duration for a single increased heating event in hours
  increased_heat_temperature: 22  # Target temperature when heating is increased
  max_increased_heat_outdoor_temperature: 15  # Maximum outdoor temperature to allow increased heating
 


pvinstallations:
  - name: Haus #name
    lat: 48.4334480
    lon: 8.7654968
    declination: 32 #inclination toward horizon 0..90 0=flat 90=vertical (e.g. wallmounted)
    azimuth: -90 # -90:East, 0:South, 90:West -180..180
    kWp: 15.695 # power in kWp
    api: #fcsolarapi
  - name: Garage  #... further installations
    lat: 48.4334480
    lon: 8.7654968
    declination: 32
    azimuth: 87
    kWp: 6.030
    api: #fcsolarapi
consumption_forecast: 
  annual_consumption: 4500 # total consumption in kWh p.a. the load profile 
  load_profile: load_profile.csv #name of the load profile file within the config folder