name: Pylint

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*


jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Fetch main branch for comparison
      run: git fetch origin main
    - name: Get changed files
      id: changed-files
      run: |
          echo "::set-output name=files::$(git diff --name-only origin/main...HEAD -- '*.py')"    
    - name: Analysing the code with pylint
      run: |
        for file in ${{ steps.changed-files.outputs.files }}; do
            pylint "$file"
        done

