name: Pylint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*


jobs:
  lint:
   runs-on: self-hosted
   #runs-on: ubuntu-latest
   strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Determine base branch and fetch it
      run: |
        if [ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]; then
          BASE_BRANCH="origin/main"
          git fetch origin main
        else
          BASE_BRANCH="upstream/main"
          git remote add upstream https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git
          git fetch upstream main
        fi
        echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

    - name: Get changed files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only $BASE_BRANCH...HEAD -- '*.py')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Analysing the code with pylint
      run: |
        for file in ${{ env.CHANGED_FILES }}; do
          pylint "$file"
        done

